# BEGIN IHK-COMPANY
0 17 * * * /opt/company/scripts/cron-runner.sh backup-company
30 16 * * * /opt/company/scripts/cron-runner.sh daily-admin-report
0 * * * * /opt/company/scripts/cron-runner.sh check-disk
0 18 * * 5 /opt/company/scripts/cron-runner.sh log-report
0 19 * * 5 /opt/company/scripts/cron-runner.sh cleanup-old-files
# END IHK-COMPANY
